variables:
  DOCKER_DRIVER: overlay2

stages:
  - build_cgraph
  - build_fsgraph
  - build_gisgraph
  - build
  - deploy

build_cgraph:
  image: node:16-alpine
  stage: build_cgraph
  cache:
    key: "npm-cgraph"
    paths:
      - cgraph/node_modules
  variables:
    NODE_ENV: production
  before_script:
    - cd cgraph
    - npm ci --include=dev
    - cd ..
  script: 
    - cd cgraph
    - npm run release
    - cd ..
  artifacts:
    paths:
      - demo
    expire_in: 1 day

build_fsgraph:
  image: node:16-alpine
  stage: build_fsgraph
  cache:
    key: "npm-fsgraph"
    paths:
      - fsgraph/node_modules
  variables:
    NODE_ENV: production
  before_script:
    - cd fsgraph
    - npm run update-locals
    - npm ci --include=dev
    - cd ..
  script:
    - cd fsgraph
    - npm run release
    - cd ..
  artifacts:
    paths:
      - demo
    expire_in: 1 day

build_gisgraph:
  image: node:16-alpine
  stage: build_gisgraph
  cache:
    key: "npm-gisgraph"
    paths:
      - gisgraph/node_modules
  variables:
    NODE_ENV: production
  before_script:
    - cd gisgraph
    - npm run update-locals
    - npm ci --include=dev
    - cd ..
  script:
    - cd gisgraph
    - npm run release
    - cd ..
  artifacts:
    paths:
      - demo
    expire_in: 1 day

build_image:
  stage: build
  image: tmaier/docker-compose
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.semograph.com
    - docker-compose build --pull
    - docker-compose push
  only:
    - master

deploy_prod:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://10.0.6.2:2376
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.semograph.com
    - docker stack deploy -c docker-compose.yml graph --with-registry-auth
  only:
    - master

