variables:
  DOCKER_DRIVER: overlay2

stages:
  - build_cgraph
  - build_fsgraph
  - build
  - deploy

build_cgraph:
  image: node:6
  stage: build_cgraph
  cache:
    key: "npm"
    paths:
      - node_modules
  before_script:
    - pushd cgraph
    - npm install
    - popd
  script: 
    - pushd cgraph
    - NODE_ENV=production nmp run release
    - popd
  artifacts:
    paths:
      - demo
    expire_in: 1 day

build_fsgraph:
  image: node:6
  stage: build_fsgraph
  cache:
    key: "npm"
    paths:
      - node_modules
  before_script:
    - pushd fsgraph
    - npm install
    - popd
  script:
    - pushd fsgraph
    - NODE_ENV=production ./node_modules/typescript/bin/tsc -p jsconfig.json
    - NODE_ENV=production ./node_modules/webpack/bin/webpack.js
    - cp dist/bundle.js ../demo/fsgraph/lib/scivi-fsgraph.min.js
    - popd
  artifacts:
    paths:
      - demo
    expire_in: 1 day

build_image:
  stage: build
  image: tmaier/docker-compose
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.semograph.com
    - docker-compose build --pull
    - docker-compose push
  only:
    - master

deploy_prod:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://10.0.6.2:2376
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.semograph.com
    - docker stack deploy -c docker-compose.yml graph --with-registry-auth
  only:
    - master

