variables:
  DOCKER_DRIVER: overlay2

stages:
  - build_static
  - build
  - deploy

build_apps:
  image: node:16-alpine
  stage: build_static
  parallel:
   matrix:
     - APP: cgraph
     - APP: fsgraph
     - APP: gisgraph
  cache:
    key: "npm-${APP}"
    paths:
      - ${APP}/node_modules
  variables:
    NODE_ENV: production
  before_script:
    - cd ${APP}
    - npm run update-locals
    - npm ci --include=dev
    - cd ..
  script: 
    - cd ${APP}
    - npm run release
    - cd ..
  artifacts:
    paths:
      - demo
    expire_in: 1 day

build_image:
  stage: build
  image: docker
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.semograph.com
    - docker-compose build --pull
    - docker-compose push
  only:
    - master

deploy_prod:
  stage: deploy
  image: docker
  variables:
    DOCKER_HOST: tcp://10.0.6.2:2376
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.semograph.com
    - docker stack deploy -c docker-compose.yml graph --with-registry-auth
  only:
    - master

