version: "3.3"
services:
  web:
    image: docker.semograph.com/semograph/graph/web:${CI_COMMIT_REF_NAME}
    build: .
    ports:
      - ${CONTAINER_PORT}:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

