var g_fsgraph_loc = {
    "en": {
        "#control": "Control",
        "#node_info": "Node info",
        "#node_list": "Node list",
        "#settings": "Settings",
        "#stats": "Stats",
        "#pause_resume": "Pause/resume layout",
        "#appearance": "Appearance",
        "#layout": "Layout",
        "#node_list_hint": "Click on list entry to center screen on specific node",
        "#hide_all_nodes": "Hide all",
        "#show_non_filtered": "Show all non-filtered",
        "#node_size_diap": "Node size diap",
        "#edge_size_diap": "Edge size diap",
        "#change_name": "Change",
        "#incoming_nodes": "Incoming links from",
        "#outcoming_nodes": "Outgoing links to",
        "#font_size": "Font size",
        "#apply": "Apply",
        "#layout_settigns": {
            "#springLength" : "Spring length",
            "#springCoeff": 'Spring coeff',
            "#edgeWeightInfluence": "Edge weight influence",
            "#outboundAttractionDistribution": "Outbound attraction distribution",
            "#linLogMode": "Lin-Log mode",
            "#barnesHutOptimize": "Barnes-Hut optimize"
        },
        "#node_types": {
            "circle": "Circle",
            "romb": "Rombus",
            "triang": "Triangle"
        },
        "#for_group": "For group",
        "#state_hint": "Show nodes with weight within specified range",
        "#fit_to_screen": "Fit to screen",
        "#metric_diameter": "Diameter:",
        "#metric_degree": "Degree (average):",
        "#metric_density": "Density:",
        "#node_color": "Node color: ",
        "#node_type": "Node type: ",
    },
    "ru": {
        "#control": "Управление",
        "#node_info": "Информация",
        "#node_list": "Вершины",
        "#settings": "Настройки",
        "#stats": "Статистика",
        "#pause_resume": "Приостановить/возобновить укладку",
        "#appearance": "Отображение",
        "#layout": "Укладка",
        "#node_list_hint": "Нажмите на вершину в списке для перехода к ней",
        "#hide_all_nodes": "Скрыть все",
        "#show_non_filtered": "Показать все согласно фильтру",
        "#node_size_diap": "Диапазон размера вершин",
        "#edge_size_diap": "Диапазон размера связей",
        "#change_name": "Изменить",
        "#incoming_nodes": "Входящие связи из",
        "#outcoming_nodes": "Исходящие связи в",
        "#font_size": "Размер ширфта",
        "#apply": "Применить",
        "#layout_settigns": {
            "#springLength" : 'Длина "пружин"',
            "#springCoeff": 'К-т сжатия "пружин"',
            "#edgeWeightInfluence": "Влияние веса связей",
            "#outboundAttractionDistribution": "Outbound attraction distribution",
            "#linLogMode": "Режим Lin-Log",
            "#barnesHutOptimize": "Оптимизация Барнса-Хата"
        },
        "#node_types": {
            "circle": "Круг",
            "romb": "Ромб",
            "triang": "Треугольник"
        },
        "#for_group": "Для группы",
        "#state_hint": "Показывать вершины, чей вес лежит в указанных диапазонах",
        "#fit_to_screen": "Подогнать под экран",
        "#metric_diameter": "Диаметр графа:",
        "#metric_degree": "Средняя стпень вершин:",
        "#metric_density": "Плотность графа:",
        "#node_color": "Цвет вершин: ",
        "#node_type": "Тип вершин: ",
    },
};