var g_loc_ru = {
    "LOCALE": "ru",
    "LOC_SEP": "Сентябрь",
    "LOC_OCT": "Октябрь",
    "LOC_NOV": "Ноябрь",
    "LOC_DEC": "Декабрь",
    "LOC_JAN": "Январь",
    "LOC_FEB": "Февраль",
    "LOC_MAR": "Март",
    "LOC_APR": "Апрель",
    "LOC_MAY": "Май",
    "LOC_JUN": "Июнь",
    "LOC_JUL": "Июль",
    "LOC_AUG": "Август",
    "LOC_INFO": "Информация о вершине",
    "LOC_NODES": "Вершины",
    "LOC_EDGES": "Рёбра",
    "LOC_SETTINGS": "Настройки",
    "LOC_FILTERS": "Фильтры",
    "LOC_GROUPS": "Кластеры",
    "LOC_SELSTUB": "Кликните на вершину, чтобы получить информацию о ней",
    "LOC_EDGETHRESHOLD": "Порог отображения рёбер:",
    "LOC_NODETHRESHOLD": "Порог отображения вершин:",
    "LOC_PASSIVETEXTALPHA": "Яркость невыделенных вершин:",
    "LOC_PASSIVEEDGEALPHA": "Яркость невыделенных рёбер:",
    "LOC_NODEFONT": "Размер шрифта вершин:",
    "LOC_RINGFONT": "Размер шрифта круговой шкалы:",
    "LOC_APPLY": "Применить",
    "LOC_SHOWALL": "Показать все",
    "LOC_HIDEALL": "Скрыть все",
    "LOC_CHANGE": "Изменить",
    "LOC_GROUP": "Кластер",
    "LOC_COLOR": "Цвет",
    "LOC_ENTERGROUP": "Перейти к кластеру",
    "LOC_LEAVEGROUP": "Выйти из кластера",
    "LOC_LINKEDNODES": "Связанные вершины:",
    "LOC_STATSTUB": "Кликните на сектор диаграммы, для получения информации по соответствующему кластеру",
    "LOC_STATCAPTION": "Статистика по кластерам (число кластеров: ",
    "LOC_MALE": "м",
    "LOC_FEMALE": "ж",
    "LOC_EDUCATION_MIDDLE": "с",
    "LOC_EDUCATION_HIGH": "в",
    "LOC_NODE_DATA": "Данные вершины",
    "LOC_FIT_TO_SCREEN": "Вписать в экран",
    "LOC_SORT_BY_RING": "Отсортировать",
    "LOC_RING_FILTER_1": "Фильтрация по сектору кольца: оба конца дуги",
    "LOC_RING_FILTER_2": "Фильтрация по сектору кольца: один конец дуги",
};
