var g_loc_ru = {
    "LOCALE": "ru",
    "LOC_SEP": "Сентябрь",
    "LOC_OCT": "Октябрь",
    "LOC_NOV": "Ноябрь",
    "LOC_DEC": "Декабрь",
    "LOC_JAN": "Январь",
    "LOC_FEB": "Февраль",
    "LOC_MAR": "Март",
    "LOC_APR": "Апрель",
    "LOC_MAY": "Май",
    "LOC_JUN": "Июнь",
    "LOC_JUL": "Июль",
    "LOC_AUG": "Август",
    "LOC_INFO": "О вершине",
    "LOC_GINFO": "О графе",
    "LOC_NODES": "Вершины",
    "LOC_EDGES": "Рёбра",
    "LOC_HYPEREDGES": "Гипер-рёбра",
    "LOC_SETTINGS": "Настройки",
    "LOC_FILTERS": "Фильтры",
    "LOC_GROUPS": "Кластеры",
    "LOC_SELSTUB": "Кликните на вершину, чтобы получить информацию о ней",
    "LOC_EDGETHRESHOLD": "Все рёбра:",
    "LOC_NODETHRESHOLD": "Все вершины:",
    "LOC_EDGELIFETIME": "Время жизни рёбер:",
    "LOC_PASSIVETEXTALPHA": "Яркость невыделенных вершин:",
    "LOC_PASSIVEEDGEALPHA": "Яркость невыделенных рёбер:",
    "LOC_NODEFONT": "Размер шрифта вершин:",
    "LOC_RINGFONT": "Размер шрифта круговой шкалы:",
    "LOC_APPLY": "Применить",
    "LOC_ALL": "∀",
    "LOC_NONE": "∅",
    "LOC_VISIBLE": "Видимы",
    "LOC_SELECTED": "Выделены",
    "LOC_CHANGE": "Изменить",
    "LOC_GROUP": "Кластер",
    "LOC_COLOR": "Цвет",
    "LOC_ENTERGROUP": "Перейти к кластеру",
    "LOC_LEAVEGROUP": "Выйти из кластера",
    "LOC_LINKEDNODES": "Связанные вершины:",
    "LOC_HYPERLINKEDNODES": "Гипер-связанные вершины:",
    "LOC_STATSTUB": "Кликните на сектор диаграммы, для получения информации по соответствующему кластеру",
    "LOC_STATCAPTION": "Статистика по кластерам (число кластеров: ",
    "LOC_MALE": "мужчины",
    "LOC_FEMALE": "женщины",
    "LOC_EDUCATION_MIDDLE": "среднее образование",
    "LOC_EDUCATION_HIGH": "высшее образование",
    "LOC_NODE_DATA": "Данные вершины",
    "LOC_FIT_TO_SCREEN": "Вписать в экран",
    "LOC_SORT_BY_RING": "Отсортировать по кольцевой шкале",
    "LOC_SORT_BY_MODULARITY": "Отсортировать по модулярности",
    "LOC_CALC_MODULARITY": "Модулярность",
    "LOC_RING_FILTER_ADD": "Добавить фильтр",
    "LOC_RING_FILTER_ARCS_GROUP": "Фильтровать дуги",
    "LOC_RING_FILTER_ARCS_GROUP_SINGLE": "Один конец (Shift+LMB)",
    "LOC_RING_FILTER_ARCS_GROUP_BOTH": "Оба конца (Alt+LMB)",
    "LOC_RING_PAINT_NODES": "Окрасить вершины",
    "LOC_FINDSTRING": "Найти по строке",
    "LOC_FINDREGEXP": "Найти по regexp",
    "LOC_NOT": "Не",
    "LOC_TREE": "Дерево",
    "LOC_SAVE_GRAPH": "Экспорт графа",
    "LOC_HELP": "Справка",
    "LOC_HELPLOC": "../css/help-ru.html",
    "LOC_GRAPHSTAT": "Статистика по графу:",
    "LOC_SUMWEIGHT": "∑ вес =",
    "LOC_CALCULATOR": "Калькулятор",
    "LOC_ADDOPERAND": "Добавть операнд",
    "LOC_OPSUM": "Сумма",
    "LOC_OPUNION": "Объединение",
    "LOC_OPDIFF": "Разность",
    "LOC_OPSYMDIFF": "Симметрическая разность",
    "LOC_OPINTERSECT": "Пересечение",
    "LOC_CALCULATE": "Вычислить",
    "LOC_CLEANCALC": "Очистить",
    "LOC_STATECALCULATED": "Текущее состояние рассчитано калькулятором. Кликните, чтобы вернуться к предыдущему.",
    "LOC_FILTER_SET": "Набор фильтров:",
    "LOC_ADD_FILTER_SET": "+",
    "LOC_REM_FILTER_SET": "–",
    "LOC_SAVE_FILTER_SET": "Сохранить в файл",
    "LOC_FILTER_SET_AVAILABLE": "Доступных наборов: ",
    "LOC_EDGE_EDIT": "Режим редактирования связей",
    "LOC_CREATE_DIRECTED_EDGES": "Создавать ориентированные связи",
    "LOC_ENTER_EDGE_TOOLTIP": "Введите название ребра"
};
