var g_loc_en = {
    "LOCALE": "en",
    "LOC_SEP": "September",
    "LOC_OCT": "October",
    "LOC_NOV": "November",
    "LOC_DEC": "December",
    "LOC_JAN": "January",
    "LOC_FEB": "February",
    "LOC_MAR": "March",
    "LOC_APR": "April",
    "LOC_MAY": "May",
    "LOC_JUN": "June",
    "LOC_JUL": "July",
    "LOC_AUG": "August",
    "LOC_INFO": "Node info",
    "LOC_NODES": "Nodes",
    "LOC_SETTINGS": "Settings",
    "LOC_GROUPS": "Groups",
    "LOC_SELSTUB": "Click on the node to get info about it",
    "LOC_EDGETHRESHOLD": "Edges displaying threshold:",
    "LOC_NODETHRESHOLD": "Nodes displaying threshold:",
    "LOC_PASSIVETEXTALPHA": "Unselected nodes lightness:",
    "LOC_PASSIVEEDGEALPHA": "Unselected edges lightness:",
    "LOC_NODEFONT": "Nodes font size:",
    "LOC_RINGFONT": "Ring scale font size:",
    "LOC_APPLY": "Apply",
    "LOC_SHOWALL": "Show all",
    "LOC_HIDEALL": "Hide all",
    "LOC_CHANGE": "Change",
    "LOC_GROUP": "Group",
    "LOC_COLOR": "Color",
    "LOC_ENTERGROUP": "Enter group",
    "LOC_LEAVEGROUP": "Leave group",
    "LOC_LINKEDNODES": "Linked nodes:",
};
